apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
spec:
  master:
    basePlugins:
    - name: kubernetes
      version: "1.30.11"
    - name: workflow-job
      version: "1145.v7f2433caa07f"
    - name: workflow-aggregator
      version: "2.7"
    - name: git
      version: "4.10.3"
    - name: job-dsl
      version: "1.78.1"
    - name: configuration-as-code
      version: "1.55"
    - name: kubernetes-credentials-provider
      version: "0.20"
    - name: github-oauth
      version: "0.37"
    - name: github
      version: "1.34.3"
    - name: docker-plugin
      version: "1.2.6"
    - name: pipeline-stage-view
      version: "2.23"
    - name: pipeline-graph-analysis
      version: "188.v3a01e7973f2c"
    - name: token-macro
      version: "280.v97a_82642793c"
    - name: github-branch-source
      version: "1583.v18d333ef7379"
    - name: pipeline-model-extensions
      version: "2.2064.v5eef7d0982b_e"
    - name: pipeline-rest-api
      version: "2.23"
    - name: token-macro
      version: "280.v97a_82642793c"
