
jenkins:
  enabled: true
  apiVersion: jenkins.io/v1alpha2
  name: jenkins
  namespace: jenkins
  image: jenkins/jenkins:2.332.1-lts-jdk11
  imagePullPolicy: IfNotPresent
  validateSecurityWarnings: false
  seedJobs:
    - id: jenkins-operator
      targets: "cicd/jobs/*.jenkins"
      description: "Jenkins Operator repository"
      repositoryBranch: master
      repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 500Mi
  basePlugins:
    - name: kubernetes
      version: "1.30.11"
    - name: workflow-job
      version: "1145.v7f2433caa07f"
    - name: workflow-aggregator
      version: "2.7"
    - name: git
      version: "4.10.3"
    - name: job-dsl
      version: "1.78.1"
    - name: configuration-as-code
      version: "1.55"
    - name: kubernetes-credentials-provider
      version: "0.20"
    - name: github-oauth
      version: "0.37"
    - name: github
      version: "1.34.3"
    - name: docker-plugin
      version: "1.2.6"
    - name: pipeline-stage-view
      version: "2.23"
    - name: pipeline-graph-analysis
      version: "188.v3a01e7973f2c"
    - name: token-macro
      version: "280.v97a_82642793c"
    - name: github-branch-source
      version: "1583.v18d333ef7379"
    - name: pipeline-model-extensions
      version: "2.2064.v5eef7d0982b_e"
    - name: pipeline-rest-api
      version: "2.23"
    - name: token-macro
      version: "280.v97a_82642793c"
  plugins:
    - name: simple-theme-plugin
      version: "0.5.1"
  # volumeMounts are mounts for Jenkins pod
  # Note that attempting to overwrite default mount settings for restricted,
  # non-configurable volumeMounts will result in Operator error
  # See https://jenkinsci.github.io/kubernetes-operator/docs/installation/#note-on-restricted-jenkins-controller-pod-volumemounts for details
  authorizationStrategy: createUser
  # http Jenkins servic
  # See https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/schema/#github.com/jenkinsci/kubernetes-operator/pkg/apis/jenkins/v1alpha2.Service for details
  #service:
  # slave Jenkins service
  # See https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/schema/#github.com/jenkinsci/kubernetes-operator/pkg/apis/jenkins/v1alpha2.Service for details
  #slaveService:

  # LivenessProbe for Jenkins Master pod
  livenessProbe:
    failureThreshold: 20
    httpGet:
      path: /login
      port: http
      scheme: HTTP
    initialDelaySeconds: 100
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 8
  # ReadinessProbe for Jenkins Master pod
  readinessProbe:
    failureThreshold: 60
    httpGet:
      path: /login
      port: http
      scheme: HTTP
    initialDelaySeconds: 120
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 8
  backup:
    enabled: false
# operator is section for configuring operator deployment
operator:
  replicaCount: 1
  image: virtuslab/jenkins-operator:49bdf51
  imagePullPolicy: IfNotPresent

webhook:
  enabled: false
cert-manager:
  startupapicheck:
    enabled: false