version: '3'
silent: true
vars:
tasks:
  install:
    cmds:
      - kubectl config set-context --current --namespace=argo
      - kubectl create namespace argo
      - kubectl config set-context --current --namespace=argo
      - task: install:manifest
    ignore_error: true

  install:manifest:
    dirs: charts
    cmds:
      - kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml