version: '3'
silent: true
tasks:
  install:
    cmds:
      - kubectl config set-context --current --namespace=gitlab
      - helm uninstall gitlab
      - kubectl create namespace gitlab
      - kubectl config set-context --current --namespace=gitlab
      - task: install:runner
    ignore_error: true

  install:runner:
    dirs: charts/gitlab
    cmds:
      - helm install gitlab gitlab/gitlab  --namespace gitlab --set global.hosts.domain={{.GITLAB_DOMAIN}} --set certmanager-issuer.email={{.EMAIL_ADDRESS}} --set nginx-ingress.enabled=false --set certmanager.install=false  --set global.ingress.configureCertmanager=false

