kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - namespaces
  - secrets
  verbs:
  - get
  - create
  - delete
  - list
  - watch
  - update

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone
subjects:
- kind: ServiceAccount
  name: drone
  namespace: drone
roleRef:
  kind: ClusterRole
  name: drone
  apiGroup: rbac.authorization.k8s.io