---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-runner
  namespace: drone
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone
subjects:
- kind: ServiceAccount
  name: drone-runner
  namespace: drone
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin