# k3d configuration file, saved as e.g. /home/me/myk3dcluster.yaml
apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: testing
servers: 1
agents: 2
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6446"
image: rancher/k3s:v1.21.5-k3s2
network: vpn2
token: DE32uLmDJgigCxko8uCPvicoG3SMHW4gBzT32mYz4 # Mock up key
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 8081:30080
    nodeFilters:
      - server:*
      - agent:*
  - port: 8082:30081
    nodeFilters:
      - server:*
      - agent:*
env:
  - envVar: bar=baz
    nodeFilters:
      - server:0
registries:
  create:
    name: registry.local.gd
    host: "0.0.0.0"
    hostPort: "5001"
  config: |
    mirrors:
      "registry.local.gd":
        endpoint:
          - http://registry.local.gd:5001
options:
  k3d:
    wait: true
    timeout: "360s"
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
    loadbalancer:
      configOverrides:
        - settings.workerConnections=2048
  k3s:
    extraArgs:
      - arg:  --tls-san=localhost,registry.local.gd,registry.localhost,127.0.0.1,localhost,power.local.gd,registry.local.gd
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
